[[headers]]
  for = "/rsvp/*"
  [headers.values]
    Content-Security-Policy = "frame-ancestors *"
    Access-Control-Allow-Origin = "https://canva-embed.com"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Credentials = "true"

[[headers]]
  for = "/countdown/*"
  [headers.values]
    Content-Security-Policy = "frame-ancestors *"
    Access-Control-Allow-Origin = "https://canva-embed.com"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Credentials = "true"
